mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('qna.urls')),
    path('accounts/login/',auth_views.LoginView.as_view(),name = 'login')
]

qna/urls.py
from django.urls import path
from qna.views import index,signup,PostQuestion,QuestionDetail,add_answer_to_question,logout_view

app_name = 'qna'

urlpatterns = [
	path('',index,name = 'index'),
	path('signup/',signup,name = 'signup'),
	path('qpost/',PostQuestion.as_view(),name = 'post'),
	path('detail/<int:pk>/',QuestionDetail.as_view(),name = 'detail'),
	path('detail/<int:pk>/answer/',add_answer_to_question,name = 'answer'),
	path('logout/',logout_view,name = 'logout'),
]

qna/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	user = models.ForeignKey(get_user_model(),on_delete = models.CASCADE,null = True)
	question = models.TextField()
	timestamp = models.DateTimeField(default = timezone.now)

	def __str__(self):
		return self.question

class Answer(models.Model):
	question = models.ForeignKey(Question,on_delete = models.CASCADE, related_name = "answers")
	answer = models.TextField()
	timestamp = models.DateTimeField(default = timezone.now)
	user = models.ForeignKey(get_user_model(),on_delete = models.CASCADE,null = True)

	def __str__(self):
		return self.answer

qna/forms.py
from django import forms
from qna.models import Question,Answer

class AnswerForm(forms.ModelForm):
	class Meta:
		model = Answer
		fields = ['answer']

qna/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate
from qna.models import Question, Answer
from qna.forms import AnswerForm
from django.views.generic.edit import CreateView
from django.views.generic import ListView,DetailView
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.
@login_required
def index(request):
	q = Question.objects.all()
	context = {'q': q}
	return render(request,'index.html',context)

class QuestionDetail(LoginRequiredMixin,DetailView):
	model = Question

class PostQuestion(LoginRequiredMixin,CreateView):
	model = Question
	fields = ['question']
	success_url = '/'

	def form_valid(self,form):
		form.instance.user = self.request.user
		return super().form_valid(form)

def signup(request):
	if request.method == 'POST':
		form = UserCreationForm(request.POST)
		if form.is_valid():
			form.save()
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password1')
			user = authenticate(username = username,password = password)
			login(request,user)
			return redirect('qna:index')
	else:
		form = UserCreationForm()
	return render(request,'registration/signup.html',{'form':form})

@login_required
def add_answer_to_question(request,pk):
	q = get_object_or_404(Question,pk = pk)
	if request.method == 'POST':
	    form = AnswerForm(request.POST)
	    if form.is_valid():
		    answer = form.save(commit = False)
		    answer.question = q
		    answer.user = request.user
		    answer.save()
		    return redirect('qna:detail',pk = q.pk)
	else:
	    form = AnswerForm()
	return render(request,'qna/answer_form.html',{'form':form})

@login_required
def logout_view(request):
	logout(request)
	return redirect('qna:index')

qna/templates/answer_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

qna/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>QnA</title>
	<!-- CSS only -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

	<!-- JS, Popper.js, and jQuery -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-light bg-light">
  <form class="form-inline">
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text" id="basic-addon1">@</span>
      </div>
      <input type="text" class="form-control" placeholder="{{request.user}}" aria-label="Username" aria-describedby="basic-addon1">
    </div>
  </form>
      {% if user.is_authenticated %}
      
      
      <a class = "btn btn-info" href="{% url 'qna:post' %}">Ask Question</a>
      <a class = "btn btn-danger" href="{% url 'qna:logout' %}">Logout</a>
      {% else %}
      
      <a class= "btn btn-danger" href="{% url 'qna:signup' %}">Register</a>
      
      {% endif %}
</nav>

<div class="container">
	{% block content %}
	<!--content here -->
	{% endblock %}
</div>
</body>
</html>

qna/templates/index.html
{% extends 'base.html' %}
{% block content %}
	<br><br>
	{% for i in q %}
	<b>{{i.question}}</b><br><br>
	<p>posted by {{i.user}} at {{i.timestamp}}</p>
	<a href="{% url 'qna:detail' i.id %}">Answer This Question</a>
	<br><br><hr>
	{% endfor %}

{% endblock %}

qna/templates/login.html
{% extends "base.html" %}
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
 {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{% endblock %}

qna/templates/qna/answer_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

qna/templates/qna/question_detail.html
{% extends 'base.html' %}
{% block content %}

<br><br><br>

<h4>{{object.question}}</h4><br>
<br><br>
published by <p>{{object.user}}</p> on {{object.timestamp}}<br>
<br><hr>

<a class="btn btn-primary btn-sm" href="{% url 'qna:answer' object.id %}" role="button">Answer</a>
<br><br>
{% for i in question.answers.all %}

<b>{{i.answer}}</b><br>
<b>{{i.timestamp}}</b><br>
submitted by {{i.user}}

<hr>

{% empty %}
No Answers
{% endfor %}

{% endblock %}

qna/templates/qna/question_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

qna/templates/question_detail.html
{% extends 'base.html' %}
{% block content %}

<br><br><br>

<h4>{{object.question}}</h4><br>
<br><br>
published by <p>{{object.user}}</p> on {{object.timestamp}}<br>
<br><hr>

<a class="btn btn-primary btn-sm" href="{% url 'qna:answer' object.id %}" role="button">Answer</a>
<br><br>
{% for i in question.answers.all %}

<b>{{i.answer}}</b><br>
<b>{{i.timestamp}}</b><br>
submitted by {{i.user}}

<hr>

{% empty %}
No Answers
{% endfor %}

{% endblock %}

qna/templates/question_form.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

qna/templates/signup.html
{% extends 'base.html' %}
{% block content %}

  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>

{% endblock %}